logo_title: 夏小正的鲜小海

style: white

favicon: /favicon.png

menu:
  归档: /archives
  友链: /links
  关于: /about
  Github: https://github.com/zhuoqun-chen

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: rwaLue5MbAoH29D7MA2TJukF-gzGzoHsz
  appKey: 10ACxwFBhOi1XQ2KY5948meH

highlight:
  enable: false

cdn:
  enabled: true
  url: https://cdn.jsdelivr.net/gh/zhuoqun-chen/zqchen.me

analytics:
  enabled: true
  googleId: G-6DBJ1VN2JX
